### ISSUE TITLE
Unable to Log In

### ISSUE THREAD

**Issue by FayZ676** [jorge-menjivar/chatbot-ui-authjs#1]
I cannot login using both Google and AuthO. I get the following error screens.
**When trying to log in with AuthO**
<img width="1728" alt="Screenshot 2023-05-16 at 9 54 42 AM" src="https://github.com/jorge-menjivar/chatbot-ui-authjs/assets/94952795/3083b956-f895-4bee-b002-62b94a38e4f8">
**When trying to log in with Google**
<img width="1728" alt="Screenshot 2023-05-16 at 9 54 50 AM" src="https://github.com/jorge-menjivar/chatbot-ui-authjs/assets/94952795/7fae0497-0fa4-429c-a226-55e888237b15">

When attempting to log in with AuthO I also get the following output from the console.
```
[next-auth][error][SIGNIN_OAUTH_ERROR] 
https://next-auth.js.org/errors#signin_oauth_error only valid absolute URLs can be requested {
  error: {
    message: 'only valid absolute URLs can be requested',
    stack: 'TypeError: only valid absolute URLs can be requested\n' +
      '    at Issuer.request (/Users/faizififita/projects/ChatbotUI/chatbot-ui/node_modules/openid-client/lib/helpers/request.js:68:11)\n' +
      '    at Issuer.discover (/Users/faizififita/projects/ChatbotUI/chatbot-ui/node_modules/openid-client/lib/issuer.js:144:38)\n' +
      '    at openidClient (/Users/faizififita/projects/ChatbotUI/chatbot-ui/node_modules/next-auth/core/lib/oauth/client.js:16:41)\n' +
      '    at getAuthorizationUrl (/Users/faizififita/projects/ChatbotUI/chatbot-ui/node_modules/next-auth/core/lib/oauth/authorization-url.js:70:49)\n' +
      '    at Object.signin (/Users/faizififita/projects/ChatbotUI/chatbot-ui/node_modules/next-auth/core/routes/signin.js:38:60)\n' +
      '    at AuthHandler (/Users/faizififita/projects/ChatbotUI/chatbot-ui/node_modules/next-auth/core/index.js:260:39)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at async NextAuthApiHandler (/Users/faizififita/projects/ChatbotUI/chatbot-ui/node_modules/next-auth/next/index.js:22:19)\n' +
      '    at async NextAuth._args$ (/Users/faizififita/projects/ChatbotUI/chatbot-ui/node_modules/next-auth/next/index.js:106:14)',
    name: 'TypeError'
  },
  providerId: 'auth0',
  message: 'only valid absolute URLs can be requested'
```
I have the following keys set in `.env.local`
```
# Auth
NEXT_PUBLIC_AUTH_ENABLED=true
NEXTAUTH_URL=http://localhost:3000
NEXTAUTH_SECRET=
NEXTAUTH_EMAIL_PATTERN=
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
AUTH0_CLIENT_ID=
AUTH0_CLIENT_SECRET=
```

**Comment by jorge-menjivar** [comment]
Did you set the callback urls? For google, in the google cloud console it should be in this format `http://localhost:3000/api/auth/callback/google`

**Comment by FayZ676** [comment]
Thank you! That fixed the google problem. What's the call back for AuthO? I've set the following.
<img width="985" alt="Screenshot 2023-05-16 at 2 31 39 PM" src="https://github.com/jorge-menjivar/chatbot-ui-authjs/assets/94952795/c7c3544f-be29-4fd0-aef9-bfbe90653302">

Still getting the screen I mentioned in the issue description though :(

**Comment by jorge-menjivar** [comment]
I think I might need to update the auth0 implementation as it looks like it takes an extra variable.

[Source](https://next-auth.js.org/providers/auth0)

**Comment by FayZ676** [comment]
Sounds good, looking forward to an update.

P.S. I sent a message to your Instagram about a potential collaboration

**Comment by jorge-menjivar** [comment]
I fixed the issue by adding the `AUTH0_ISSUER` variable. However, this specific package is no longer used, and so all the commits are being pushed directly to the [main repo](https://github.com/jorge-menjivar/chatbot-ui). Thanks!
